name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "10/0 0/0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 1422c0867bb23304ff54e3d325fbe2ee
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
